<MenuWidget>:
    Label:
        font_size:dp(60)
        text:root.parent.menutitle
        pos_hint:{"center_x":.5,"center_y":.6}

    Button:
        font_size:dp(20)
        text:root.parent.menubuttontitle
        pos_hint:{"center_x":.5,"center_y":.4}
        size_hint:.2,.1
        on_press:root.parent.startbutton()

        background_normal:''
        background_color:1,0,0,1